---
date: "2022-10-24"
sections:
- block: hero
  content:
    cta:
      label: '**Get Started**'
      url: https://hugoblox.com/templates/
    cta_alt:
      label: Ask a question
      url: https://discord.gg/z8wNYzb
    cta_note:
      label: '<div style="text-shadow: none;"><a class="github-button" href="https://github.com/HugoBlox/hugo-blox-builder"
        data-icon="octicon-star" data-size="large" data-show-count="true" aria-label="Star">Star
        Hugo Blox Builder</a></div><div style="text-shadow: none;"><a class="github-button"
        href="https://github.com/HugoBlox/theme-academic-cv" data-icon="octicon-star"
        data-size="large" data-show-count="true" aria-label="Star">Star the Academic
        template</a></div>'
    image:
      filename: hero-academic.png
    text: |-
      **Generated by Hugo Blox Builder - the FREE, Hugo-based open source website builder trusted by 500,000+ sites.**

      **Easily build anything with blocks - no-code required!**

      From landing pages, second brains, and courses to academic resumés, conferences, and tech blogs.

      <!--Custom spacing-->
      <div class="mb-3"></div>
      <!--GitHub Button JS-->
      <script async defer src="https://buttons.github.io/buttons.js"></script>
    title: Hugo Academic Theme
  demo: true
  design:
    background:
      gradient_end: '#1976d2'
      gradient_start: '#004ba0'
      text_color_light: true
- block: about.biography
  content:
    title: 
    username: admin
  id: about

title: ""
type: landing
---
